---
- name: create_dir
  include: create_dir.yml
  tags: create_dir
- name: genarate_kube_config
  include: genarate_kube_config.yml
  tags: genarate_kube_config
- name: distribute_k8s_file
  include: distribute_k8s_file.yml
  tags: distribute_k8s_file
- name: distribute_apiserver
  include: distribute_apiserver.yml
  tags: distribute_apiserver
- name: distribute_controller_manager
  include: distribute_controller_manager.yml
  tags: distribute_controller_manager
- name: distribute_scheduler
  include: distribute_scheduler.yml
  tags: distribute_scheduler
- name: create_some_roles
  include: create_some_roles.yml
  tags: create_some_roles  
- name: make_master_labels_and_taints
  include: make_master_labels_and_taints.yml
  tags: make_master_labels_and_taints
- name: copy_admin_config
  include: copy_admin_config.yml
  tags: copy_admin_config